name: Test Coverage

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Running Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use None.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Coverage
        run: npm run test:coverage --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"